---
title: "Annual Progress Review"
author: "Thomas Boughen"
format: 
  revealjs:
    logo: imgs/University_of_Newcastle_Coat_of_Arms.png
    theme: serif
engine: knitr
---


# Extreme Value Theory

## Continuous Extremes

## Discrete Extremes

## Integral Generalised Pareto Distribution

## Spliced Mixture

# Network Generative Models

## General Preferential Attachment {.smaller}

Starting with $G_1 = (V_1, E_1) = (\{1,\ldots,m_0\}, \emptyset)$. At each time $t>1$,  $G_t = (V_t, E_t)$ is generated by the following rules:

. . .

**Growth**: Add a new vertex to the vertex set i.e. 
$$
V_t = V_{t-1} \cup \{t\}
$$

. . .

**Preferential Attachment**: Add $m\le m_0$ edges connecting the new vertex to the existing vertices selected at random with weights proportional to a function of their degree i.e.:

$$
E_t  = E_{t-1} \cup \{\tilde e_1,\ldots,\tilde e_m\}
$$

where $\tilde e_j = \{t,\tilde v\}$ and $\tilde v = i$ with weights 

$$
\displaystyle\frac{g(d(i))}{\sum_{w\in V_{t-1}} g(d(i))}, \qquad i\in V_{t-1}
$$


## Special Cases {.smaller .center}
:::: {.columns}

::: {.column width="50%"}
### Barabási-Albert

$$
g(k) = k
$$

#### Degree Distribution

$$
f(k) = \frac{2m(m+1)}{k(k+1)(k+2)}
$$
If $m=1$:
$$
f(k) = \frac{4}{k(k+1)(k+2)}
$$
Belongs to Fréchet domain of attraction. 

$$
\mathcal D (\Phi_2)
$$ 

:::

::: {.column width="50%"}
### Uniform Attachment
$$
g(k) = c
$$

#### Degree Distribution

$$
f(k) \approx \displaystyle\frac{e}{m}\exp\left(-\displaystyle\frac{k}{m}\right)
$$
If $m=1$:

$$
f(k) = \left(1\over2\right)^k
$$

Recoverable to Gumbel domain of attraction.

$$
\mathcal D(\Lambda)
$$

:::

::::

# Analysis

## Degree distributions

## IGP model fit

## GPA analyses

## 

##









